# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c7950d558917c9bc648e60bb632eece0c9f79c5da6fe688ea296cadd2df8c0cdf60aa5a078dbe2c8b241dd4db8149097386ba457dc933d1f13f18bded4260a33

test:
  secret_key_base: 718de9897fe24c0bdf492e8700dc078f5d5156e0f57b32aa45a7e777168294ba636590f869c055ae8fd5d98721fd85eab0bc8dc57dbc6d469a513a0d3d4cf346

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
